name: Bing Indexing

on:
  workflow_dispatch:   # ✅ 수동 실행 가능
  #schedule:
  #  - cron: "0 18 * * 0"   # 매주 월요일 오전 3시 (KST), GitHub Actions는 UTC 기준이라 +9시간


jobs:
  run-bing-indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install advertools requests beautifulsoup4 python-dateutil

      - name: Decode BING_KEY_JSON
        run: echo "${{ secrets.BING_KEY_JSON }}" | base64 -d > bing_key.json

      - name: Run Bing indexing script
        run: python Bing_Index.py


